import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/services", "routes/services.tsx"),
  route("/services/peinture-interieure-paris", "routes/service-peinture.tsx"),
  route("/services/pose-parquet-paris", "routes/service-parquet.tsx"),
  route("/services/pose-carrelage-paris", "routes/service-carrelage.tsx"),
  route("/services/pose-sol-vinyle-paris", "routes/service-sol-vinyle.tsx"),
  route("/services/pose-plaques-de-platre-paris", "routes/service-placo.tsx"),
  route("/services/nettoyage-apres-travaux-paris", "routes/service-nettoyage.tsx"),
  route("/zones-intervention", "routes/zones-intervention.tsx"),
  route("/renovation-interieure/boulogne-billancourt", "routes/renovation-boulogne-billancourt.tsx"),
  route("/renovation-interieure/neuilly-sur-seine", "routes/renovation-neuilly-sur-seine.tsx"),
  route("/renovation-interieure/levallois-perret", "routes/renovation-levallois-perret.tsx"),
  route("/renovation-interieure/vincennes", "routes/renovation-vincennes.tsx"),
  route("/a-propos", "routes/propos.tsx"),
  route("/about", "routes/about-redirect.tsx"),
  route("/contact", "routes/contact.tsx"),
  route("/merci", "routes/merci.tsx"),
  route("/politique-de-confidentialite", "routes/politique-confidentialite.tsx"),
  route("/sitemap.xml", "routes/sitemap.ts"),
  route("/robots.txt", "routes/robots.ts"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
